version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - corpo-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/corpo_event
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    networks:
      - corpo-network
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./doc/merise/corpo-event-db-script-docker.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=corpo_event
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  corpo-network:
    driver: bridge

volumes:
  pgdata: 